### ISSUE TITLE
macOS 10.14.6 Gazebo 8 dyld: Symbol not found

### ISSUE THREAD

**Issue by lingjiekong** [osrf/homebrew-simulation#1021]
brew install gazebo8.

Then, issue gazebo in command line and get below error message.

dyld: Symbol not found: __ZN6gazebo3gui10DataLogger16staticMetaObjectE
  Referenced from: /usr/local/Cellar/gazebo8/8.6.0_5/lib/libgazebo_gui.8.dylib
  Expected in: flat namespace
 in /usr/local/Cellar/gazebo8/8.6.0_5/lib/libgazebo_gui.8.dylib
Abort trap: 6

**Comment by scpeters** [comment]
can you try using the `--build-from-source` flag when building gazebo?

**Comment by scpeters** [comment]
I'm not sure what caused this issue, but I think it is not occurring anymore, and also gazebo8 is at end-of-life.
