### ISSUE TITLE
sofa now on github

### ISSUE THREAD

**Issue by ahundt** [osrf/homebrew-simulation#106]
https://github.com/osrf/homebrew-simulation/blob/master/sofa.rb

should now point to:
https://github.com/sofa-framework/sofa

**Comment by scpeters** [comment]
pull requests are welcome

**Comment by ahundt** [comment]
was just an fyi, not actually using the formula at the moment. Thanks for letting me know!

**Comment by scpeters** [comment]
sorry, I didn't mean to be terse, I just thought that it would have been a similar level of effort to modify the formula using the browser interface and submit a pull request

I've never used sofa either; I added it a while ago when I heard about it

**Comment by ahundt** [comment]
No worries! didn't know it was that easy, it was a good exercise. Thanks :-)
