### ISSUE TITLE
Error compiling gazebo9 ModelTreeWidget.cc

### ISSUE THREAD

**Issue by egradman** [osrf/homebrew-simulation#1123]
Hi, I'm installing gazebo9 (for use with px4-sim).

I ran `brew install osrf/homebrew-simulation/gazebo9 --verbose` to get this build log:

https://gist.github.com/egradman/3aabc6b4d6a3242ba81d4cdb9d87bc55

Here's the good (bad) bits:

```
/tmp/gazebo9-20200912-95689-1ea5hlg/gazebo-9.14.0/gazebo/gui/model/ModelTreeWidget.cc:165:56: error: use of undeclared identifier '_1'
      boost::bind(&ModelTreeWidget::OnSaveModel, this, _1)));
```

**Comment by egradman** [comment]
FYI, same error on gazebo10

**Comment by scpeters** [comment]
thanks, we've merged a fix upstream in https://github.com/osrf/gazebo/commit/c55942ed348580317ea77312f7efce5c7937a49c; I'll add it as a patch to the gazebo9 formula

**Comment by scpeters** [comment]
if you want to test the patch, there is example syntax in https://github.com/osrf/homebrew-simulation/pull/992/commits/f4e822a13ab55826a3fa9fee5f6b8673cb75c64d

**Comment by scpeters** [comment]
patch in #1128

**Comment by egradman** [comment]
worked for me!  Thanks for fixing it so quickly.
