### ISSUE TITLE
Gazebo 9/11 on macOS catatalina 10.15.7 won't work due to freeimage

### ISSUE THREAD

**Issue by lucarag** [osrf/homebrew-simulation#1344]
Hi,

So, basically I'm trying to install gazebo on a macbook pro with macOS catatalina 10.15.7.
I successfully install it (either version 11 or 9) with
brew install gazebo11 (or gazebo9 - _of course when I try to install the alternative version I remove the former first_)
when I try running gazebo, however, there is this error:

$ gazebo
dyld: Library not loaded: /usr/local/opt/freeimage/lib/libfreeimage.dylib
  Referenced from: /usr/local/bin/gazebo
  Reason: Incompatible library version: gazebo requires version 3.0.0 or later, but libfreeimage.dylib provides version 0.0.0
Abort trap: 6

Now, I checked at the path above and the required library is actually present (screenshot below). Even try reinstalling it with brew (brew install and brew reinstall freeimage) is able to fix the problem. This same files and paths can be found in Cellar. 

Is there a way to solve this?

Thank you in advance.

<img width="1440" alt="Schermata 2021-02-25 alle 16 15 17" src="https://user-images.githubusercontent.com/72132319/109173840-95f23900-7784-11eb-849a-02f4c1ea20d4.png">

**Comment by scpeters** [comment]
closing as this conversation has moved to https://github.com/osrf/gazebo/issues/2946
