### ISSUE TITLE
Rebuild bottles for protobuf 3.17.0

### ISSUE THREAD

**Issue by scpeters** [osrf/homebrew-simulation#1463]
The protobuf 3.17.0 bottle is pending in https://github.com/Homebrew/homebrew-core/pull/77373 and will break all our bottles once it is merged. We should do the following:

1. Remove bottle blocks for everything downstream of protobuf, staring from `ignition-msgs*` and `gazebo*` so that they will build from source until bottle are rebuilt
2. Rebuild bottles incrementally.
 - [x] msgs
 - [x] fuel-tools
 - [x] transport
 - [x] gui
 - [x] sensors
 - [x] gazebo
 - [x] launch
 - [x] collections
 - [x] gazebo9
 - [x] gazebo11

**Comment by j-rivero** [comment]
I think I can take this one, the homebrew-core was merged some minutes ago.

> Rebuild bottles incrementally.

Does it makes sense to use the same pull request to do it? Changing several revisions at once will work?

**Comment by scpeters** [comment]
> I think I can take this one, the homebrew-core was merged some minutes ago.
> 
> > Rebuild bottles incrementally.
> 
> Does it makes sense to use the same pull request to do it? Changing several revisions at once will work?

it can work, but an sporadic infrastructure problem is more likely to affect them all and make the builds longer. it's a bit safer to cluster them together: one for each ignition stack (citadel, dome, edifice, fortress), and one (or 2) for gazebo9 / 11. it is more effort, but in my experience with build failures, it's nicer to segregate the packages

**Comment by scpeters** [comment]
since all the bottles are gone at the moment, another alternative is to increment all the ign-msgs* versions in a single PR, then ign-transport* and go gradually that way. we could try to rebuild them all at once and see if it works, but it may take 12+ hours

**Comment by scpeters** [comment]
thanks for the help @j-rivero; I'll let you take it from here

**Comment by scpeters** [comment]
the build farm is clear so I got it started with #1466
