### ISSUE TITLE
gazebo build error on Mac 10.11.6

### ISSUE THREAD

**Issue by studiocardo** [osrf/homebrew-simulation#149]
Hi

Tried to build gazebo with the following command on my MBP running 10.11.6.  I ran "brew update" twice prior to the build and still getting this message.  

Any advice on how to proceed is much appreciated!!!
# $ curl -ssL http://get.gazebosim.org | sh
# GAZEBO INSTALLATION SCRIPT

This script is installing the latest stable version of
Gazebo Simulator available from your package manager

package-id: org.macosforge.xquartz.pkg
version: 2.7.94
volume: /
location:
install-time: 1474091503
Already up-to-date.
==> Installing gazebo7 from osrf/simulation
==> Installing dependencies for osrf/simulation/gazebo7: protobuf-c, bullet, simbody
==> Installing osrf/simulation/gazebo7 dependency: protobuf-c
==> Downloading https://homebrew.bintray.com/bottles/protobuf-c-1.2.1_2.el_capitan.bottle.tar.gz
Already downloaded: /Users/howard/Library/Caches/Homebrew/protobuf-c-1.2.1_2.el_capitan.bottle.tar.gz
==> Pouring protobuf-c-1.2.1_2.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/protobuf-c/1.2.1_2: 12 files, 287.2K
==> Installing osrf/simulation/gazebo7 dependency: bullet
==> Using the sandbox
==> Downloading https://github.com/bulletphysics/bullet3/archive/2.83.7.tar.gz
Already downloaded: /Users/howard/Library/Caches/Homebrew/bullet-2.83.7.tar.gz
==> cmake -DINSTALL_EXTRA_LIBS=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/bullet/2.83.7 -DUSE_DOUBLE_PRECISION=ON -DBUILD_BULLET2_DEMOS=OFF
==> make
==> make install
🍺  /usr/local/Cellar/bullet/2.83.7: 456 files, 6.5M, built in 30 seconds
==> Installing osrf/simulation/gazebo7 dependency: simbody
==> Downloading https://github.com/simbody/simbody/archive/Simbody-3.5.4.tar.gz
Already downloaded: /Users/howard/Library/Caches/Homebrew/simbody-3.5.4.tar.gz
==> Downloading https://github.com/scpeters/simbody/commit/a37deef08af530b57601251900fadee0d0be6cfd.diff
Already downloaded: /Users/howard/Library/Caches/Homebrew/simbody--patch-0b99f7b6df46ddcc43094b29ba834896490fe5a76ceaa15f646b3b4579fed51e.diff
==> Patching
==> Applying a37deef08af530b57601251900fadee0d0be6cfd.diff
patching file cmake/pkgconfig/simbody.pc.in
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/simbody/3.5.4 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LA
==> make doxygen
==> make install
🍺  /usr/local/Cellar/simbody/3.5.4: 3,847 files, 118.7M, built in 4 minutes 31 seconds
==> Installing osrf/simulation/gazebo7
==> Downloading http://gazebosim.org/distributions/gazebo/releases/gazebo-7.3.1.tar.bz2
Already downloaded: /Users/howard/Library/Caches/Homebrew/gazebo7-7.3.1.tar.bz2
==> Downloading https://gist.githubusercontent.com/scpeters/9199370/raw/afe595587e38737c537124a3652db99de026c272/brew_python_fix.patch
Already downloaded: /Users/howard/Library/Caches/Homebrew/gazebo7--patch-c4774f64c490fa03236564312bd24a8630963762e25d98d072e747f0412df18e.patch
==> Downloading https://bitbucket.org/osrf/gazebo/commits/90b82ee6efe79d83dc9fa4f9706e050e658d1221/raw/
Already downloaded: /Users/howard/Library/Caches/Homebrew/gazebo7--patch-73f3724ce0123cd71968b8b03822d45a3b893ca40f746feed76870c9b29e7603
==> Patching
==> Applying brew_python_fix.patch
patching file deps/opende/CMakeLists.txt
==> Applying raw
patching file gazebo/util/LogPlay.cc
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/gazebo7/7.3.1_5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=
==> make install
Last 15 lines from /Users/howard/Library/Logs/Homebrew/gazebo7/02.make:
cd /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/gazebo/physics && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DBT_USE_DOUBLE_PRECISION -DHAVE_OPENGL -DLIBBULLET_VERSION=2.83 -DLIBBULLET_VERSION_GT_282 -DMAC_OS_X_VERSION=1080 -Dgazebo_physics_EXPORTS -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/test/gtest/include -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1 -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build -isystem /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/deps/opende/include -isystem /usr/local/include -I/usr/local/Cellar/tinyxml2/4.0.1/include -isystem /usr/local/Cellar/ignition-math2/2.5.0/include/ignition/math2 -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/RTShaderSystem -isystem /usr/local/Cellar/ogre/1.7.4/include -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/Terrain -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/Paging -isystem /usr/local/Cellar/sdformat4/4.1.1_1/include/sdformat-4.1 -isystem /usr/local/opt/tinyxml/include -I/usr/local/Cellar/bullet/2.83.7/include/bullet -I/usr/local/Cellar/bullet/2.83.7/include -isystem /usr/local/Cellar/simbody/3.5.4/include/simbody  -stdlib=libc++  -Wall -Wextra -Wno-long-long -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wfloat-equal -Wshadow -Winit-self -Wswitch-default -Wmissing-include-dirs -pedantic -std=c++11   -O3 -DNDEBUG -mssse3 -msse3 -msse -msse2  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11 -fPIC   -fPIC -I/usr/local/Cellar/bullet/2.83.7/include/bullet -I/usr/local/Cellar/bullet/2.83.7/include -I"/usr/local/Cellar/simbody/3.5.4/include/simbody" -o CMakeFiles/gazebo_physics.dir/State.cc.o -c /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/gazebo/physics/State.cc
[ 57%] Building CXX object gazebo/physics/CMakeFiles/gazebo_physics.dir/SurfaceParams.cc.o
cd /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/gazebo/physics && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DBT_USE_DOUBLE_PRECISION -DHAVE_OPENGL -DLIBBULLET_VERSION=2.83 -DLIBBULLET_VERSION_GT_282 -DMAC_OS_X_VERSION=1080 -Dgazebo_physics_EXPORTS -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/test/gtest/include -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1 -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build -isystem /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/deps/opende/include -isystem /usr/local/include -I/usr/local/Cellar/tinyxml2/4.0.1/include -isystem /usr/local/Cellar/ignition-math2/2.5.0/include/ignition/math2 -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/RTShaderSystem -isystem /usr/local/Cellar/ogre/1.7.4/include -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/Terrain -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/Paging -isystem /usr/local/Cellar/sdformat4/4.1.1_1/include/sdformat-4.1 -isystem /usr/local/opt/tinyxml/include -I/usr/local/Cellar/bullet/2.83.7/include/bullet -I/usr/local/Cellar/bullet/2.83.7/include -isystem /usr/local/Cellar/simbody/3.5.4/include/simbody  -stdlib=libc++  -Wall -Wextra -Wno-long-long -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wfloat-equal -Wshadow -Winit-self -Wswitch-default -Wmissing-include-dirs -pedantic -std=c++11   -O3 -DNDEBUG -mssse3 -msse3 -msse -msse2  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11 -fPIC   -fPIC -I/usr/local/Cellar/bullet/2.83.7/include/bullet -I/usr/local/Cellar/bullet/2.83.7/include -I"/usr/local/Cellar/simbody/3.5.4/include/simbody" -o CMakeFiles/gazebo_physics.dir/SurfaceParams.cc.o -c /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/gazebo/physics/SurfaceParams.cc
[ 57%] Building CXX object gazebo/physics/CMakeFiles/gazebo_physics.dir/UserCmdManager.cc.o
cd /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/gazebo/physics && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DBT_USE_DOUBLE_PRECISION -DHAVE_OPENGL -DLIBBULLET_VERSION=2.83 -DLIBBULLET_VERSION_GT_282 -DMAC_OS_X_VERSION=1080 -Dgazebo_physics_EXPORTS -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/test/gtest/include -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1 -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build -isystem /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/deps/opende/include -isystem /usr/local/include -I/usr/local/Cellar/tinyxml2/4.0.1/include -isystem /usr/local/Cellar/ignition-math2/2.5.0/include/ignition/math2 -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/RTShaderSystem -isystem /usr/local/Cellar/ogre/1.7.4/include -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/Terrain -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/Paging -isystem /usr/local/Cellar/sdformat4/4.1.1_1/include/sdformat-4.1 -isystem /usr/local/opt/tinyxml/include -I/usr/local/Cellar/bullet/2.83.7/include/bullet -I/usr/local/Cellar/bullet/2.83.7/include -isystem /usr/local/Cellar/simbody/3.5.4/include/simbody  -stdlib=libc++  -Wall -Wextra -Wno-long-long -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wfloat-equal -Wshadow -Winit-self -Wswitch-default -Wmissing-include-dirs -pedantic -std=c++11   -O3 -DNDEBUG -mssse3 -msse3 -msse -msse2  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11 -fPIC   -fPIC -I/usr/local/Cellar/bullet/2.83.7/include/bullet -I/usr/local/Cellar/bullet/2.83.7/include -I"/usr/local/Cellar/simbody/3.5.4/include/simbody" -o CMakeFiles/gazebo_physics.dir/UserCmdManager.cc.o -c /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/gazebo/physics/UserCmdManager.cc
[ 57%] Building CXX object gazebo/physics/CMakeFiles/gazebo_physics.dir/World.cc.o
cd /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/gazebo/physics && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DBT_USE_DOUBLE_PRECISION -DHAVE_OPENGL -DLIBBULLET_VERSION=2.83 -DLIBBULLET_VERSION_GT_282 -DMAC_OS_X_VERSION=1080 -Dgazebo_physics_EXPORTS -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/test/gtest/include -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1 -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build -isystem /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/deps/opende/include -isystem /usr/local/include -I/usr/local/Cellar/tinyxml2/4.0.1/include -isystem /usr/local/Cellar/ignition-math2/2.5.0/include/ignition/math2 -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/RTShaderSystem -isystem /usr/local/Cellar/ogre/1.7.4/include -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/Terrain -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/Paging -isystem /usr/local/Cellar/sdformat4/4.1.1_1/include/sdformat-4.1 -isystem /usr/local/opt/tinyxml/include -I/usr/local/Cellar/bullet/2.83.7/include/bullet -I/usr/local/Cellar/bullet/2.83.7/include -isystem /usr/local/Cellar/simbody/3.5.4/include/simbody  -stdlib=libc++  -Wall -Wextra -Wno-long-long -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wfloat-equal -Wshadow -Winit-self -Wswitch-default -Wmissing-include-dirs -pedantic -std=c++11   -O3 -DNDEBUG -mssse3 -msse3 -msse -msse2  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11 -fPIC   -fPIC -I/usr/local/Cellar/bullet/2.83.7/include/bullet -I/usr/local/Cellar/bullet/2.83.7/include -I"/usr/local/Cellar/simbody/3.5.4/include/simbody" -o CMakeFiles/gazebo_physics.dir/World.cc.o -c /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/gazebo/physics/World.cc
[ 57%] Building CXX object gazebo/physics/CMakeFiles/gazebo_physics.dir/WorldState.cc.o
cd /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/gazebo/physics && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DBT_USE_DOUBLE_PRECISION -DHAVE_OPENGL -DLIBBULLET_VERSION=2.83 -DLIBBULLET_VERSION_GT_282 -DMAC_OS_X_VERSION=1080 -Dgazebo_physics_EXPORTS -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/test/gtest/include -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1 -I/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build -isystem /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/deps/opende/include -isystem /usr/local/include -I/usr/local/Cellar/tinyxml2/4.0.1/include -isystem /usr/local/Cellar/ignition-math2/2.5.0/include/ignition/math2 -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/RTShaderSystem -isystem /usr/local/Cellar/ogre/1.7.4/include -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/Terrain -isystem /usr/local/Cellar/ogre/1.7.4/include/OGRE/Paging -isystem /usr/local/Cellar/sdformat4/4.1.1_1/include/sdformat-4.1 -isystem /usr/local/opt/tinyxml/include -I/usr/local/Cellar/bullet/2.83.7/include/bullet -I/usr/local/Cellar/bullet/2.83.7/include -isystem /usr/local/Cellar/simbody/3.5.4/include/simbody  -stdlib=libc++  -Wall -Wextra -Wno-long-long -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wfloat-equal -Wshadow -Winit-self -Wswitch-default -Wmissing-include-dirs -pedantic -std=c++11   -O3 -DNDEBUG -mssse3 -msse3 -msse -msse2  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11 -fPIC   -fPIC -I/usr/local/Cellar/bullet/2.83.7/include/bullet -I/usr/local/Cellar/bullet/2.83.7/include -I"/usr/local/Cellar/simbody/3.5.4/include/simbody" -o CMakeFiles/gazebo_physics.dir/WorldState.cc.o -c /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/gazebo/physics/WorldState.cc
[ 57%] Linking CXX shared library libgazebo_physics.dylib
cd /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/gazebo/physics && /usr/local/Cellar/cmake/3.6.2/bin/cmake -E cmake_link_script CMakeFiles/gazebo_physics.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -stdlib=libc++  -Wall -Wextra -Wno-long-long -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wno-unused-value -Wfloat-equal -Wshadow -Winit-self -Wswitch-default -Wmissing-include-dirs -pedantic -std=c++11   -O3 -DNDEBUG -mssse3 -msse3 -msse -msse2  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11 -dynamiclib -Wl,-headerpad_max_install_names   -Wl,-undefined -Wl,dynamic_lookup -compatibility_version 7.0.0 -current_version 7.3.1 -o libgazebo_physics.7.3.1.dylib -install_name /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/gazebo/physics/libgazebo_physics.7.dylib CMakeFiles/gazebo_physics.dir/ode/ODEBallJoint.cc.o CMakeFiles/gazebo_physics.dir/ode/ODECollision.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEFixedJoint.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEGearboxJoint.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEHeightmapShape.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEHinge2Joint.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEHingeJoint.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEJoint.cc.o CMakeFiles/gazebo_physics.dir/ode/ODELink.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEMesh.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEMeshShape.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEMultiRayShape.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEPhysics.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEPolylineShape.cc.o CMakeFiles/gazebo_physics.dir/ode/ODERayShape.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEScrewJoint.cc.o CMakeFiles/gazebo_physics.dir/ode/ODESliderJoint.cc.o CMakeFiles/gazebo_physics.dir/ode/ODESurfaceParams.cc.o CMakeFiles/gazebo_physics.dir/ode/ODEUniversalJoint.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletBallJoint.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletCollision.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletFixedJoint.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletHeightmapShape.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletHinge2Joint.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletHingeJoint.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletJoint.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletLink.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletMesh.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletMeshShape.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletMotionState.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletMultiRayShape.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletPhysics.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletPolylineShape.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletRayShape.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletScrewJoint.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletSliderJoint.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletSurfaceParams.cc.o CMakeFiles/gazebo_physics.dir/bullet/BulletUniversalJoint.cc.o CMakeFiles/gazebo_physics.dir/bullet/gzBtUniversalConstraint.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyBallJoint.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyCollision.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyFixedJoint.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyHeightmapShape.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyHinge2Joint.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyHingeJoint.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyJoint.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyLink.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyMesh.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyMeshShape.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyModel.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyMultiRayShape.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyPhysics.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyPlaneShape.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyPolylineShape.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyRayShape.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyScrewJoint.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodySliderJoint.cc.o CMakeFiles/gazebo_physics.dir/simbody/SimbodyUniversalJoint.cc.o CMakeFiles/gazebo_physics.dir/Actor.cc.o CMakeFiles/gazebo_physics.dir/Base.cc.o CMakeFiles/gazebo_physics.dir/BoxShape.cc.o CMakeFiles/gazebo_physics.dir/Collision.cc.o CMakeFiles/gazebo_physics.dir/CollisionState.cc.o CMakeFiles/gazebo_physics.dir/Contact.cc.o CMakeFiles/gazebo_physics.dir/ContactManager.cc.o CMakeFiles/gazebo_physics.dir/CylinderShape.cc.o CMakeFiles/gazebo_physics.dir/Entity.cc.o CMakeFiles/gazebo_physics.dir/Gripper.cc.o CMakeFiles/gazebo_physics.dir/HeightmapShape.cc.o CMakeFiles/gazebo_physics.dir/Inertial.cc.o CMakeFiles/gazebo_physics.dir/Joint.cc.o CMakeFiles/gazebo_physics.dir/JointController.cc.o CMakeFiles/gazebo_physics.dir/JointState.cc.o CMakeFiles/gazebo_physics.dir/Light.cc.o CMakeFiles/gazebo_physics.dir/LightState.cc.o CMakeFiles/gazebo_physics.dir/Link.cc.o CMakeFiles/gazebo_physics.dir/LinkState.cc.o CMakeFiles/gazebo_physics.dir/MapShape.cc.o CMakeFiles/gazebo_physics.dir/MeshShape.cc.o CMakeFiles/gazebo_physics.dir/Model.cc.o CMakeFiles/gazebo_physics.dir/ModelState.cc.o CMakeFiles/gazebo_physics.dir/MultiRayShape.cc.o CMakeFiles/gazebo_physics.dir/PhysicsIface.cc.o CMakeFiles/gazebo_physics.dir/PhysicsEngine.cc.o CMakeFiles/gazebo_physics.dir/PhysicsFactory.cc.o CMakeFiles/gazebo_physics.dir/PlaneShape.cc.o CMakeFiles/gazebo_physics.dir/PolylineShape.cc.o CMakeFiles/gazebo_physics.dir/Population.cc.o CMakeFiles/gazebo_physics.dir/PresetManager.cc.o CMakeFiles/gazebo_physics.dir/RayShape.cc.o CMakeFiles/gazebo_physics.dir/Road.cc.o CMakeFiles/gazebo_physics.dir/Shape.cc.o CMakeFiles/gazebo_physics.dir/SphereShape.cc.o CMakeFiles/gazebo_physics.dir/State.cc.o CMakeFiles/gazebo_physics.dir/SurfaceParams.cc.o CMakeFiles/gazebo_physics.dir/UserCmdManager.cc.o CMakeFiles/gazebo_physics.dir/World.cc.o CMakeFiles/gazebo_physics.dir/WorldState.cc.o  -L/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/test  -L/usr/local/Cellar/tinyxml2/4.0.1/lib  -L/usr/local/Cellar/ogre/1.7.4/lib  -L/usr/local/Cellar/bullet/2.83.7/lib  -L/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/deps/libccd  -L/usr/local/Cellar/simbody/3.5.4/lib ../util/libgazebo_util.7.3.1.dylib ../../deps/opende/libgazebo_ode.7.3.1.dylib ../../deps/opende/OPCODE/libgazebo_opcode.7.3.1.dylib -lBulletSoftBody -lBulletDynamics -lBulletCollision -lLinearMath /usr/local/Cellar/simbody/3.5.4/lib/libSimTKsimbody.dylib /usr/local/Cellar/simbody/3.5.4/lib/libSimTKmath.dylib /usr/local/Cellar/simbody/3.5.4/lib/libSimTKcommon.dylib -framework Accelerate -framework Accelerate -framework Accelerate -lpthread -ldl -lm ../transport/libgazebo_transport.7.3.1.dylib ../msgs/libgazebo_msgs.7.3.1.dylib ../common/libgazebo_common.7.3.1.dylib ../math/libgazebo_math.7.3.1.dylib /usr/lib/libdl.dylib /usr/local/lib/libfreeimage.dylib -ltinyxml -lcurl /usr/local/lib/libtar.dylib /usr/local/lib/libtbb.dylib /usr/local/Cellar/sdformat4/4.1.1_1/lib/libsdformat.dylib /usr/local/Cellar/ignition-math2/2.5.0/lib/libignition-math2.dylib -framework OpenAL /usr/local/lib/libprotobuf.dylib -ltinyxml2 /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_signals-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_program_options-mt.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib ../../deps/opende/GIMPACT/libgazebo_gimpact.7.3.1.dylib ../../deps/opende/ou/libgazebo_opende_ou.7.3.1.dylib ../../deps/libccd/libgazebo_ccd.7.3.1.dylib -lpthread -lm -Wl,-rpath,/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/test -Wl,-rpath,/usr/local/Cellar/tinyxml2/4.0.1/lib -Wl,-rpath,/usr/local/Cellar/ogre/1.7.4/lib -Wl,-rpath,/usr/local/Cellar/bullet/2.83.7/lib -Wl,-rpath,/tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/deps/libccd -Wl,-rpath,/usr/local/Cellar/simbody/3.5.4/lib
cd /tmp/gazebo7-20161007-15136-1qjgxus/gazebo-7.3.1/build/gazebo/physics && /usr/local/Cellar/cmake/3.6.2/bin/cmake -E cmake_symlink_library libgazebo_physics.7.3.1.dylib libgazebo_physics.7.dylib libgazebo_physics.dylib
[ 57%] Built target gazebo_physics
make: **\* [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/osrf/homebrew-simulation/issues

**Comment by scpeters** [comment]
Thanks for the report; we just noticed this as well. I believe it is related to a new version of boost that was just released. I think it may be fixed by the patches in #148

**Comment by tarasrudyy** [comment]
Hi,

I've tried patched version, same error still.

Regards

**Comment by scpeters** [comment]
@tarasrudyy can you build with the `--verbose` flag and then post the gist logs?

~~~
brew install --verbose gazebo7
brew gist-logs gazebo7
~~~

**Comment by tarasrudyy** [comment]
@scpeters sure

https://gist.github.com/fdbcee56e7ba08559b71ef5be23feeca

**Comment by scpeters** [comment]
It's having a problem finding qt headers:

~~~
/tmp/gazebo7-20161010-1475-8bfz7z/gazebo-7.3.1/gazebo/rendering/RenderEngine.cc:30:11: fatal error: 'QtCore/qglobal.h' file not found
# include <QtCore/qglobal.h>
          ^
~~~

What do you see in the following folder:

~~~
/usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/Headers
~~~

I'm guessing that is where it wants to find `QtCore/qglobal.h`

**Comment by tarasrudyy** [comment]
It's empty. I've just tried to `brew uninstall qt` and `brew install qt`

> qt: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.

**Comment by scpeters** [comment]
Oh, I didn't realize that qt4 is not supported on macOS 10.12. That is a very big problem since gazebo currently needs qt4. Sorry that you're the one who had to discover it.

We are currently working on supporting qt5 in gazebo. It currently compiles but does run properly on homebrew (works on Ubuntu though). I'll try to keep you updated on this status. In the meantime, I'm going to recommend that people wait to upgrade to macOS 10.12 if they want to use gazebo.

**Comment by scpeters** [comment]
In the meantime, there is a tap that may work for you (from https://github.com/Homebrew/homebrew-core/pull/5216#issuecomment-251478385 )

~~~
brew install cartr/qt4/qt
~~~

**Comment by tarasrudyy** [comment]
Thank you Steven! I'm looking forward for Gazebo 8. If no luck with macOS then good old Ubuntu :)

**Comment by tarasrudyy** [comment]
`brew install cartr/qt4/qt` works fine for me
