### ISSUE TITLE
gazebo9,11 bottles broken by dartsim 6.12.1

### ISSUE THREAD

**Issue by scpeters** [osrf/homebrew-simulation#1665]
The minor version of dartsim in homebrew-core was recently upgraded from 6.11.1 to 6.12.1 in https://github.com/Homebrew/homebrew-core/pull/89141, which has broken our gazebo bottles:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-one_liner-homebrew-amd64&build=2234)](https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/2234/) https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/2234/

We should open separate pull requests to bump the revision for gazebo9 and gazebo11 and rebuild the bottles. To do this, on a new branch run the following command for gazebo11:

~~~
brew bump-revision gazebo11 --message="for dartsim"
~~~

push the branch, open a pull request, and comment `build bottle`.

Then do the same for gazebo9.

**Comment by nkalupahana** [comment]
^ can confirm, this has broken our builds that use gazebo11: https://github.com/nkalupahana/ros2-foxy-macos/runs/4176692550?check_suite_focus=true

**Comment by nkalupahana** [comment]
All fixed for me!
