### ISSUE TITLE
Need El Capitan and Sierra bottles for simbody.

### ISSUE THREAD

**Issue by lloydc99** [osrf/homebrew-simulation#171]
Building simbody from source will cause Travis CI builds to time-out.

I've built two new bottles for simbody and put them on DropBox.

https://www.dropbox.com/sh/xc6vyuthg6b4lo5/AAB2uXSaVLpvp1YlEsV6C8Gwa?dl=0

**Comment by scpeters** [comment]
We now have a sierra build machine and have built our first sierra bottle in #232. We will continue building sierra bottles for the other packages as we are able.

**Comment by scpeters** [comment]
bottles for simbody are now available
