### ISSUE TITLE
Add formula for ogre2.3

### ISSUE THREAD

**Issue by srmainwaring** [osrf/homebrew-simulation#1825]
# Enhancement

https://github.com/ignitionrobotics/ign-rendering/pull/553 has an upstream dependency on ogre2.3. This issue is a request for a new formula to support that version of ogre.

I have done some preliminary testing on macOS with ignition-rendering / ogre2.3 documented here https://github.com/ignitionrobotics/ign-rendering/pull/553#issuecomment-1055440013. 

I have used a script that builds and installs ogre2.3 using the same installation directory modifications as used in the ogre2.2 formula, and the upgraded version of ogre appears to be working well.

**Comment by scpeters** [comment]
added in https://github.com/osrf/homebrew-simulation/pull/1956
