### ISSUE TITLE
How do you manage bottles etc?

### ISSUE THREAD

**Issue by ahundt** [osrf/homebrew-simulation#214]
I assume you guys have some backend stuff that manages your bottles and such. Any chance that's released/recorded somewhere? I'd love to be able to replicate that functionality for my own tap. :-)

**Comment by scpeters** [comment]
We have some scripts in our release-tools repository. You're free to look at them, and we may be able to answer some brief questions, but you're welcome to read the code:

* https://bitbucket.org/osrf/release-tools/src/default/jenkins-scripts/lib/homebrew_bottle_creation.bash
* https://bitbucket.org/osrf/release-tools/src/default/jenkins-scripts/dsl/core.dsl
* https://bitbucket.org/osrf/release-tools/src/default/jenkins-scripts/lib/homebrew_bottle_pullrequest.bash

**Comment by scpeters** [comment]
Discussion seems to have died down. Please re-open if anyone has any more questions.
