### ISSUE TITLE
make: *** [all] Error 2  on mac m1 Monterey

### ISSUE THREAD

**Issue by tot1342** [osrf/homebrew-simulation#2221]
When I try to install ignition-math6 for gazebo7 (and gazebo11) on mac m1 Monterey  I get error: 
[ 97%] Built target math
make: *** [all] Error 2

==> Formula
Tap: osrf/simulation
Path: /opt/homebrew/Library/Taps/osrf/homebrew-simulation/Formula/ignition-math6.rb
==> Configuration
HOMEBREW_VERSION: 4.0.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ba6d87eed9ce31f42fa2b33a4e6067d9cf17f13f
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 91c2e435b2f354084c9183c602081840ac9558e3
Core tap last commit: 4 hours ago
Core tap branch: master
Core tap JSON: 22 Feb 14:33 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.F2JkZ0te1Y/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /opt/homebrew/opt/openssl@1.1:/opt/homebrew/opt/readline:/opt/homebrew/opt/sqlite:/opt/homebrew/opt/ruby:/opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /opt/homebrew/opt/python@3.11/Frameworks
PKG_CONFIG_PATH: /opt/homebrew/opt/ignition-cmake2/lib/pkgconfig:/opt/homebrew/opt/openssl@1.1/lib/pkgconfig:/opt/homebrew/opt/readline/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/xz/lib/pkgconfig:/opt/homebrew/opt/python@3.11/lib/pkgconfig:/opt/homebrew/opt/libyaml/lib/pkgconfig:/opt/homebrew/opt/ruby/lib/pkgconfig:/opt/homebrew/opt/pybind11/share/pkgconfig:/opt/homebrew/opt/eigen/share/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/12
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
ACLOCAL_PATH: /opt/homebrew/share/aclocal
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:/opt/homebrew/opt/cmake/bin:/opt/homebrew/opt/doxygen/bin:/opt/homebrew/opt/pybind11/bin:/opt/homebrew/opt/pkg-config/bin:/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/xz/bin:/opt/homebrew/opt/python@3.11/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/opt/python@3.11/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: osrf/simulation/ignition-math6 6.13.0 did not build
Logs:
     /Users/rasta/Library/Logs/Homebrew/ignition-math6/00.options.out
     /Users/rasta/Library/Logs/Homebrew/ignition-math6/01.cmake.cc
     /Users/rasta/Library/Logs/Homebrew/ignition-math6/01.cmake
     /Users/rasta/Library/Logs/Homebrew/ignition-math6/02.make.cc
     /Users/rasta/Library/Logs/Homebrew/ignition-math6/build
     /Users/rasta/Library/Logs/Homebrew/ignition-math6/02.make
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/osrf/homebrew-simulation/issues

These open issues may also help:
Fix ignition-math6 https://github.com/osrf/homebrew-simulation/pull/1910
Pybind11 CMake error when installing ignition-math6 with homebrew https://github.com/osrf/homebrew-simulation/issues/1872

**Comment by scpeters** [comment]
there isn't enough information here to debug, please reopen if the problem persists
