### ISSUE TITLE
Tests that use ign-math6 python bindings are failing in CI

### ISSUE THREAD

**Issue by azeey** [osrf/homebrew-simulation#2269]
Python binding tests are failing with

```
ImportError while importing test module '/Users/jenkins/jenkins-agent/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/ign-gazebo/python/test/testFixture_TEST.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../../ign-gazebo/python/test/testFixture_TEST.py:20: in <module>
    from ignition.math import Vector3d
E   ModuleNotFoundError: No module named 'ignition.math'
```

in https://github.com/gazebosim/gz-sim/pull/1989 (see https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/10054/testReport/).
I think the issue is python@3.11 is the version of python in the test, but the ign-math6 bottle was [built](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/1158/) with python@3.10. Do we need to rebuild the ign-math6 bottle or is there a better solution? Does https://github.com/osrf/homebrew-simulation/pull/1910 help with this?

**Comment by scpeters** [comment]
python bindings have been rebuilt since this time. see also #2834
