### ISSUE TITLE
All protobuf dependent bottles are broken (gz-msgs*, gz-fuel-tools*, etc)

### ISSUE THREAD

**Issue by scpeters** [osrf/homebrew-simulation#2274]
Please supply your brew configuration:

### Brew configuration

from https://build.osrfoundation.org/view/ign-garden/job/ignition_fuel-tools8-install_bottle-homebrew-amd64/222/

~~~
$ brew config
+ brew config
HOMEBREW_VERSION: 4.0.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9d0b7361d1a197949dbb47b761405075f83983b7
Last commit: 34 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1f9b329aacf9df9df60f7bd87f8d169f7d30e2c1
Core tap last commit: 12 minutes ago
Core tap branch: master
Core tap JSON: 01 Jun 11:12 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GIT_EMAIL: osrfbuild@osrfoundation.org
HOMEBREW_GIT_NAME: OSRF Build Bot
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_UPDATE_TO_TAG: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.41.0 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.6-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
+ brew doctor
Your system is ready to brew.
~~~

### Brew linkage test result

~~~
$ + brew linkage --test ignition-fuel-tools8
Broken dependencies:
  /usr/local/opt/gz-msgs9/lib/libgz-msgs9.9.dylib (gz-msgs9)
  /usr/local/opt/protobuf/lib/libprotobuf.32.dylib (protobuf)
~~~

### Checklist

- [X] Identify change in homebrew-core that broke the bottle: https://github.com/Homebrew/homebrew-core/commit/37b747c394edd631861fe8a807d1b86df8fd810a, part of https://github.com/Homebrew/homebrew-core/pull/131405
- [x] Identify list of affected formulae
    - [x] gz-msgs* and dependents
    - [x] gz-transport* and dependents
    - [x] gazebo11
- [x] Remove broken bottles: for each affected formula, run `brew bump-revision --remove-bottle-block`
    - [x] gz-msgs* and dependents https://github.com/osrf/homebrew-simulation/pull/2275
    - [x] gz-transport* and dependents https://github.com/osrf/homebrew-simulation/pull/2275
    - [x] gazebo11 https://github.com/osrf/homebrew-simulation/pull/2275
- [x] Patches for broken formulae
    - [x] https://github.com/osrf/homebrew-simulation/pull/2279
    - [x] https://github.com/osrf/homebrew-simulation/pull/2281
    - [x] https://github.com/osrf/homebrew-simulation/pull/2288
    - [x] https://github.com/osrf/homebrew-simulation/pull/2291
    - [x] https://github.com/osrf/homebrew-simulation/pull/2294
    - [x] https://github.com/osrf/homebrew-simulation/pull/2298
    - [x] gz-msgs https://github.com/gazebosim/gz-msgs/pull/346
    - [x] gz-transport https://github.com/gazebosim/gz-transport/pull/405
    - [x] gz-gui https://github.com/gazebosim/gz-gui/pull/544
    - [x] gz-sensors https://github.com/gazebosim/gz-sensors/pull/351, https://github.com/gazebosim/gz-sensors/pull/353
    - [x] gz-sim https://github.com/gazebosim/gz-sim/pull/2006
    - [x] https://github.com/gazebosim/gazebo-classic/pull/3331
- [x] Rebuild btoken bottles
    - [x] Garden: gz-msgs9 and dependents
        - [x] https://github.com/osrf/homebrew-simulation/pull/2284
        - [ ] gz-fuel-tools8 https://github.com/Homebrew/homebrew-core/pull/133746
        - [ ] gz-gui7 https://github.com/osrf/homebrew-simulation/pull/2299
        - [ ] gz-sensors7 https://github.com/osrf/homebrew-simulation/pull/2299
        - [ ] gz-sim7
        - [ ] gz-launch6
        - [ ] gz-garden
    - [x] Fortress: gz-msgs8 and dependents
        - [x] https://github.com/osrf/homebrew-simulation/pull/2283
        - [x] gz-gui6 https://github.com/osrf/homebrew-simulation/pull/2292
        - [x] gz-sim6 https://github.com/osrf/homebrew-simulation/pull/2292
        - [x] gz-launch5 https://github.com/osrf/homebrew-simulation/pull/2292
        - [x] gz-fortress https://github.com/osrf/homebrew-simulation/pull/2292
    - [x] Citadel: gz-msgs5 and dependents
        - [x] https://github.com/osrf/homebrew-simulation/pull/2277
        - [x] https://github.com/osrf/homebrew-simulation/pull/2278
        - [x] https://github.com/osrf/homebrew-simulation/pull/2282
        - [x] gz-gui3 https://github.com/osrf/homebrew-simulation/pull/2293
        - [x] gz-sim3 https://github.com/osrf/homebrew-simulation/pull/2293
        - [x] gz-launch2 https://github.com/osrf/homebrew-simulation/pull/2293
        - [x] gz-citadel https://github.com/osrf/homebrew-simulation/pull/2293
    - [X] gazebo11 https://github.com/osrf/homebrew-simulation/pull/2295

**Comment by scpeters** [comment]
This was precipitated by the merge of protobuf 22.5 in https://github.com/Homebrew/homebrew-core/pull/131405, but a complicating factor is that protobuf-c doesn't yet support this new version (https://github.com/protobuf-c/protobuf-c/issues/544), and `gz-msgs*` uses `protobuf-c`, so for consistency we should switch all of our formulae to `protobuf@21` to match the change in `protobuf-c` from https://github.com/Homebrew/homebrew-core/commit/37b747c394edd631861fe8a807d1b86df8fd810a. This will likely cause other issues because as a versioned formula, `protobuf@21` is keg-only, which means that it does not symlink into the standard `brew --prefix` (`/usr/local` for intel machines) and will likely require extra environment variables to be set by our CI and users building from source (similar to [this code](https://github.com/gazebo-tooling/release-tools/blob/00e4d2c0ddb9a290ffb7db75dcb092f612f9c33a/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash#L130-L173)).

**Comment by scpeters** [comment]
Disabling broken bottles in https://github.com/osrf/homebrew-simulation/pull/2275

**Comment by scpeters** [comment]
ideally, we would only have `protobuf@21` and not `protobuf` installed on a system, but `protobuf` is an indirect dependency of `gz-common5` (via `grpc` and `gdal`), so this may get messy for packages like gz-gui, gz-sensors, and gz-sim that depend on both `gz-msgs*` and `gz-common5`

**Comment by traversaro** [comment]
>  gz-msgs* uses protobuf-c,

I probably be missing something really obvious, but by inspecting the CMake of gz-msgs I could not find any protobuf-c dependency, only the regular protobuf dependency. Where does the dependency on protobuf-c come from?

**Comment by scpeters** [comment]
> > gz-msgs* uses protobuf-c,
> 
> I probably be missing something really obvious, but by inspecting the CMake of gz-msgs I could not find any protobuf-c dependency, only the regular protobuf dependency. Where does the dependency on protobuf-c come from?

I think you're right; this dependency has been in use for a while but I'm not sure why

**Comment by scpeters** [comment]
> > > gz-msgs* uses protobuf-c,
> > 
> > 
> > I probably be missing something really obvious, but by inspecting the CMake of gz-msgs I could not find any protobuf-c dependency, only the regular protobuf dependency. Where does the dependency on protobuf-c come from?
> 
> I think you're right; this dependency has been in use for a while but I'm not sure why

I thought the `protoc` compiler was only provided by `protobuf-c`, but that is not the case now at least; maybe it was always wrong. I'm glad you noticed this though, because this will let us stop using `protobuf-c` and switch back from `protobuf@21` to `protobuf`!

**Comment by scpeters** [comment]
@traversaro thanks for being on top of this with https://github.com/gazebosim/gz-msgs/pull/346 and other patches in that series!

**Comment by traversaro** [comment]
> @traversaro thanks for being on top of this with [gazebosim/gz-msgs#346](https://github.com/gazebosim/gz-msgs/pull/346) and other patches in that series!

FYI I reached some more problems in gz-sim https://github.com/conda-forge/gz-sim-feedstock/pull/16#issuecomment-1584175017, but I am not investigating. Note that those could be conda-forge-specific.

**Comment by scpeters** [comment]
I've rebuilt most of citadel and fortress bottles (except gz-gui6 and gz-sim+), but I'm having trouble with some of the garden bottles because `gz-common5` has an indirect dependency on `protobuf@21` via `apache-arrow` / `gdal`, and this is mixing up the bottle builds of `gz-fuel-tools8` and others.

**Comment by scpeters** [comment]
> I've rebuilt most of citadel and fortress bottles (except gz-gui6 and gz-sim+), but I'm having trouble with some of the garden bottles because `gz-common5` has an indirect dependency on `protobuf@21` via `apache-arrow` / `gdal`, and this is mixing up the bottle builds of `gz-fuel-tools8` and others.

related apache-arrow issues: https://github.com/apache/arrow/issues/35986, https://github.com/apache/arrow/issues/35987

**Comment by carlocab** [comment]
I might be able to unblock you with Homebrew/homebrew-core#133623, since apache/arrow#35987 suggests that that's the fix for newer `grpc`/`protobuf` for `apache-arrow`.

**Comment by scpeters** [comment]
> I might be able to unblock you with [Homebrew/homebrew-core#133623](https://github.com/Homebrew/homebrew-core/pull/133623), since [apache/arrow#35987](https://github.com/apache/arrow/issues/35987) suggests that that's the fix for newer `grpc`/`protobuf` for `apache-arrow`.

thanks @carlocab!

**Comment by scpeters** [comment]
I think our dependency issues with apache-arrow will resolve with https://github.com/Homebrew/homebrew-core/pull/133496

**Comment by carlocab** [comment]
> I think our dependency issues with apache-arrow will resolve with https://github.com/Homebrew/homebrew-core/pull/133496

Unfortunately I think we may be blocked by `protobuf-c`, since some dependents depend on both `apache-arrow` and `protobuf-c`, so we can't mix their `protobuf`/`grpc` dependencies. https://github.com/Homebrew/homebrew-core/pull/133746

**Comment by scpeters** [comment]
a new protobuf was merged, with what I assume is an ABI change because our bottles broke, so I removed them again in https://github.com/Homebrew/homebrew-core/pull/133818

**Comment by traversaro** [comment]
> a new protobuf was merged, with what I assume is an ABI change because our bottles broke, so I removed them again in [Homebrew/homebrew-core#133818](https://github.com/Homebrew/homebrew-core/pull/133818)

Unfortunatly since protobuf 4.22 (or 22, depending to which version scheme you use) now patch (or minor, again depending if you refer to 4.23.3 or 23.3) version explicitly break the SOVERSION/ABI, see:
* https://github.com/protocolbuffers/protobuf/pull/10355
* https://github.com/protocolbuffers/protobuf/issues/10323
* https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4075#issuecomment-1564566666

**Comment by scpeters** [comment]
I've patched and rebuilt citadel, fortress and gazebo11 bottles at this point, but garden bottles are still broken, due to `gz-common5`'s indirect dependency on `protobuf@21` (via apache-arrow and gdal). I've explored removing `gdal` as a dependency of `gz-common5`, which would disable its `geospatial` component and found that this requires changes in `gz-physics6`, which I believe I have made in https://github.com/gazebosim/gz-physics/pull/516, but I found that it would require changes in `gz-rendering7`, which may be more extensive.

I then refocused my efforts on patching `protobuf-c` to support the new protobuf and may have come up with something in https://github.com/protobuf-c/protobuf-c/pull/556
