### ISSUE TITLE
Error trying to download Gazebo on MacOS

### ISSUE THREAD

**Issue by ah19190** [osrf/homebrew-simulation#2287]
Please supply your brew configuration:

~~~
$ brew config
HOMEBREW_VERSION: 4.0.22
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9d01e1deafca35f30b709b5f6a031faaff9642ec
Last commit: 22 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1bb288d7d16edee9310d310f054b7c908f05ee64
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 13 Jun 09:53 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-x86_64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
~~~

If you are reporting a build failure, please supply the build logs
with the `--verbose` flag:

These are the logs. I am unable to install Gazebo. 
I am using a Macbook Pro 2019 Intel i5, running MacOS Ventura 13.4 
When using homebrew to install Gazebo binary using the method listed in the installation guide,I get errors during the installation of the gz-fuel-tools8 dependency for gz-garden. 
These errors occurred while building the source code of gz-fuel-tools8. 

Whereas when I try to install gazebo7, I get the errors stated in the log below. 
https://gist.github.com/ah19190/95fc27d951b044654bc6305ee0eb7d34

I am just trying to get gazebo to run on my machine for a project, so any help would be appreciated. 

~~~
brew install gazebo7 --verbose
brew gist-logs gazebo7
~~~

then include the link in the issue. Thanks!

**Comment by scpeters** [comment]
gazebo7 is past it's end of life date and will be disabled soon. The currently supported version is gazebo11
