### ISSUE TITLE
gz-common5 bottle is broken due to bump in gdal

### ISSUE THREAD

**Issue by azeey** [osrf/homebrew-simulation#2328]
### Brew configuration

~~~
$ brew config

HOMEBREW_VERSION: 4.1.3-31-g24b6b34
ORIGIN: https://github.com/Homebrew/brew
HEAD: 24b6b3494d5495eb07ca0777524ff9d4b1e3f91d
Last commit: 4 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7f1c27a065c0469fe9e2de04c59eaf7e9e267fe0
Core tap last commit: 5 months ago
Core tap branch: master
Core tap JSON: 03 Aug 14:40 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.3-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
~~~

### Brew linkage test result

~~~
$ brew linkage --test gz-common5

Broken dependencies:
  /usr/local/opt/gdal/lib/libgdal.32.dylib (gdal)
~~~

### Checklist

- [x] Identify change in homebrew-core that broke the bottle: https://github.com/Homebrew/homebrew-core/pull/134485
- [x] Identify list of affected formulae
  - gz-fuel-tools8
  - gz-fuel-tools9
  - gz-garden
  - gz-gui7
  - gz-gui8
  - gz-launch6
  - gz-launch7
  - gz-physics6
  - gz-rendering7
  - gz-rendering8
  - gz-sensors7
  - gz-sensors8
  - gz-sim7
  - gz-sim8

- [x] Remove broken bottles: for each affected formula, run `brew bump-revision --remove-bottle-block`
    - [x] https://github.com/osrf/homebrew-simulation/pull/2329
- [x] Rebuild broken bottles
    - [x] https://github.com/osrf/homebrew-simulation/pull/2331

**Comment by scpeters** [comment]
bottles we rebuilt in https://github.com/osrf/homebrew-simulation/pull/2331
