### ISSUE TITLE
Rebuild bottles after protobuf 24.1 is in homebrew-core

### ISSUE THREAD

**Issue by scpeters** [osrf/homebrew-simulation#2339]
Placeholder issue for when https://github.com/Homebrew/homebrew-core/pull/139954/ is merged. It should be similar to https://github.com/osrf/homebrew-simulation/issues/2314

Please supply your brew configuration:

### Brew configuration

~~~
$ brew config

~~~

### Brew linkage test result

~~~
$ brew linkage --test gz-common5

~~~

### Checklist

- [x] Identify change in homebrew-core that broke the bottle 
    - https://github.com/Homebrew/homebrew-core/pull/139954
    - https://github.com/Homebrew/homebrew-core/pull/139025
- [X] Identify list of affected formulae
    - gz-msgs* and dependents
    - gazebo11
- [X] Remove broken bottles: for each affected formula, run `brew bump-revision --remove-bottle-block`
    - [X] https://github.com/osrf/homebrew-simulation/pull/2348
    - [X] https://github.com/osrf/homebrew-simulation/pull/2363
- [ ] Rebuild broken bottles
    - [x] Garden
        - [x] https://github.com/osrf/homebrew-simulation/pull/2350
        - [x] https://github.com/osrf/homebrew-simulation/pull/2368
    - [x] Fortress
        - [x] https://github.com/osrf/homebrew-simulation/pull/2387
    - [x] Citadel
      - [x] https://github.com/osrf/homebrew-simulation/pull/2377
    - [x] Gazebo11
      - [x] gazebo11: rebuild after protobuf upgrade #2380

**Comment by scpeters** [comment]
the subsequent update of abseil in https://github.com/Homebrew/homebrew-core/pull/139025 has broken these formulae again. I'll remove broken formulae again

**Comment by j-rivero** [comment]
@scpeters we probably can close this one, right?

**Comment by scpeters** [comment]
yes, these bottles are rebuilt
