### ISSUE TITLE
abseil bump broke bottles

### ISSUE THREAD

**Issue by j-rivero** [osrf/homebrew-simulation#2587]
The bump for abseil https://github.com/Homebrew/homebrew-core/commit/b794c6a136a70e7f15ab9002d8d228627f9a4d07 broke a good bunch of our bottles.

Let's try to rebuild the bottles:

 -  [x] Disabled broken bottles https://github.com/osrf/homebrew-simulation/pull/2588
 -  [ ] Rebuild the bottles
     - [x] Citadel https://github.com/osrf/homebrew-simulation/pull/2589
     - [x] Fortress https://github.com/osrf/homebrew-simulation/pull/2589
     - [x] Garden https://github.com/osrf/homebrew-simulation/pull/2591
     - [x] Harmonic https://github.com/osrf/homebrew-simulation/pull/2592
     - [x] gazebo11 https://github.com/osrf/homebrew-simulation/pull/2590

**Comment by scpeters** [comment]
Under `Rebuild the bottles`, I added a checklist for each Gazebo collection and gazebo11
