### ISSUE TITLE
gazebo failed to build on 10.9.5

### ISSUE THREAD

**Issue by kdorsel** [osrf/homebrew-simulation#29]
Failing to build gazebo while trying to install ROS Hydro.

https://gist.github.com/anonymous/3d72d247d7126bb44660

**Comment by scpeters** [comment]
The protobuf issues were resolved in [gazebo pull request 1346](https://bitbucket.org/osrf/gazebo/pull-request/1346/fix-build-for-os-x-1010-1304-1289/diff), though there are now some other issues with boost 1.57 that prevent gazebo from building. I have a fix for them waiting for code review. I'll close this when gazebo is building again.

**Comment by scpeters** [comment]
`brew install gazebo` should be working again, as of https://github.com/osrf/homebrew-simulation/commit/ea3464712046520b657f6b748ce5a8c86c5913c5
