### ISSUE TITLE
RViz Mesh format / OGRE version

### ISSUE THREAD

**Issue by LorenzMeier** [osrf/homebrew-simulation#31]
@wjwwood You updated the Ogre meshes to v1.8+ in this commit:
https://github.com/ros-visualization/rviz/commit/1aad3d89feba77d7a356888436ed83bc701a97f6

However, the brew tap here only offers Ogre 1.7. The default recommended install version from the ROS website (indigo) requires Ogre 1.8. Which leaves me wondering: What setup are you running on your machine? Any chance to get the homebrew formulas updated to 1.8?

**Comment by scpeters** [comment]
We now have an ogre1.9 formula with bottles.
