### ISSUE TITLE
Simbody 3.5 fails to compile on 10.10

### ISSUE THREAD

**Issue by kt10aan** [osrf/homebrew-simulation#33]
Here is the related gist:
https://gist.github.com/19efd74e1c0bfb4167f5

The previous version was working fine on my machines.

**Comment by scpeters** [comment]
Fixed in https://github.com/simbody/simbody/issues/321, released in [simbody 3.5.1](https://github.com/simbody/simbody/releases/tag/Simbody-3.5.1), and formula updated in c842564ac3f15a09d5c82d521f121946a1fab07c.

**Comment by scpeters** [comment]
@kt10aan thanks for the bug report!

**Comment by kt10aan** [comment]
Thanks for the extremely fast fix!

**Comment by kt10aan** [comment]
There appears to be the wrong SHA1 has though in the updated formula:

```
==> Downloading https://github.com/simbody/simbody/archive/Simbody-3.5.1.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: d11eeecee8fe5e13e885a38c087843fce3399d19
Actual: 7db86ae232c579527a8bae6103316f68e2d99ba0
```

**Comment by scpeters** [comment]
fixed the sha1 in https://github.com/osrf/homebrew-simulation/commit/c601c2270b731249fc58af599c2f8cdb841052b9

Not sure how I had it wrong.

**Comment by sherm1** [comment]
My fault -- it took me a couple of tries to get the 3.5.1 release done. I did it once and then deleted it and re-created it. I think you might have pointed at the first attempt.
