### ISSUE TITLE
Link to sdformat-2.2.1 source is broken

### ISSUE THREAD

**Issue by jslee02** [osrf/homebrew-simulation#35]
sdformat.rb seem not working since [the link](https://github.com/osrf/homebrew-simulation/blob/master/sdformat.rb#L5) is broken. Is this temporary?

**Comment by jslee02** [comment]
It looks like [the server is down](http://www.downforeveryoneorjustme.com/old.gazebosim.org/assets/distributions/sdformat-2.2.1.tar.bz2), and this was reported in [gazebo issue tracker]( https://bitbucket.org/osrf/gazebo/issue/1421/gazebo-install-fails-on-mac-osx-1010).

**Comment by scpeters** [comment]
It seems to be fixed now.
