### ISSUE TITLE
fails to build on 10.10.3 - again :(

### ISSUE THREAD

**Issue by xtrntr** [osrf/homebrew-simulation#40]
https://gist.github.com/694f8253040bc6af9fe0

**Comment by scpeters** [comment]
Did you `brew up`? It's having the same error that the new patch should have fixed. Also, you can re-open the old issue next time instead of opening a new one.

**Comment by xtrntr** [comment]
Hi, brew up worked and i have gazebo installed now. Sorry that i did not know about that.

**Comment by scpeters** [comment]
No worries!
