### ISSUE TITLE
brew install gazebo8/9 fails building on High Sierra

### ISSUE THREAD

**Issue by TSC21** [osrf/homebrew-simulation#441]
Currently on a Travis CI building job, with the following script lines:
```
    ...
    brew tap osrf/simulation;
    brew install opencv ${GAZEBO_VERSION};
    ...
```
where `GAZEBO_VERSION` corresponds to the respective Gazebo version to install.

The following build error is reported: https://travis-ci.org/PX4/sitl_gazebo/jobs/395170004#L1351.

If it helps, I may add the `--verbose` tag if required. This started to happen 2/3 days ago, for each build.

Any tips debugging it are appreciated.

**Comment by scpeters** [comment]
it will be fixed by https://github.com/osrf/homebrew-simulation/pull/440

I'm just waiting for the travis CI to finish testing, then I will merge it. Sorry for the outage.

* https://bitbucket.org/osrf/gazebo/issues/2483/gazebo-compilation-broken-with-protobuf-36

**Comment by scpeters** [comment]
bottles should now be fixed

**Comment by TSC21** [comment]
Thanks!
