### ISSUE TITLE
sdformat8 (gz11 branch) failing to `#include <any>`

### ISSUE THREAD

**Issue by chapulina** [osrf/homebrew-simulation#471]
This was introduced in [this PR](https://bitbucket.org/osrf/sdformat/pull-requests/438/removal-of-boost/diff#comment-67720520) removing boost.

**Comment by scpeters** [comment]
It's failing because `<any>` isn't on high_sierra: https://github.com/osrf/homebrew-simulation/pull/437#issuecomment-404894304

**Comment by scpeters** [comment]
mojave bottles now available
