### ISSUE TITLE
gazebo does not find root.sdf when homebrew is installed in non-default location

### ISSUE THREAD

**Issue by fredowski** [osrf/homebrew-simulation#479]
I installed gazebo 8 together with sdformat5 in a non-default location. When I run gazebo I
see the following output:

```
FriedrichsMacBook:Firmware fritz$ gazebo
Error [parser.cc:80] Unable to load file[collision.sdf]
Error [parser.cc:80] Unable to load file[collision.sdf]
Error [parser.cc:64] Unable to find or open SDF file[root.sdf]
Error [parser.cc:64] Unable to find or open SDF file[root.sdf]
FriedrichsMacBook:Firmware fritz$ 
```

I turns out that the sdformat5 is using the bottled version which includes hardcoded paths to the
share/sdformat directory where collision.sdf and root.sdf are stored. 

When I build sdformat5 from source, then gazebo starts without errors.  I opened
PR #478 to use the bottled version only if build and install directory are the same.

**Comment by scpeters** [comment]
Thanks for reporting this; we have been trying to make relocatable packages, and I believe the cmake files are now relocatable, but the location of the SDF description files is not, as you have found. A workaround may be to set the `SDF_PATH` environment variable. In the meantime, I will look at #478.

**Comment by fredowski** [comment]
Thanks for the review and the report to upstream!
