### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Autonomoustic** [osrf/homebrew-simulation#519]
here is the gist-logs - https://gist.github.com/Autonomoustic/2910b6e54726633ad72e89f7b6b9f158

**Comment by scpeters** [comment]
it complains about the Accelerate framework. I've seen a problem related to this framework before with simbody. Can you try unlinking simbody and trying the build again?

**Comment by scpeters** [comment]
closing as inactive; please re-open if the issue persists

**Comment by scpeters** [comment]
I'm seeing this issue now too. I believe it's caused when the simbody bottle is built on a machine that has a full Xcode installation. I'm going to try to fix the simbody formula so that a full xcode installation doesn't matter.
