### ISSUE TITLE
Gazebo 8: unable to install on macOS 10.14 "Mojave"

### ISSUE THREAD

**Issue by pietrodn** [osrf/homebrew-simulation#528]
I can't figure out which error causes this.
[Here are the logs](https://gist.github.com/pietrodn/7abf2f33c72095325637eb5961b79c77).

**Comment by scpeters** [comment]
this should be fixed by #521

**Comment by scpeters** [comment]
fixed by #521

**Comment by pietrodn** [comment]
I confirm this is fixed by #521. I'm able to successfully compile the PX4 SITL.
Thank you for your precious work! 👍👍👍
