### ISSUE TITLE
ignition-transport3 cannot build in High Sierra with recent brew

### ISSUE THREAD

**Issue by iPsych** [osrf/homebrew-simulation#844]
When following below installation commands,

> rosdep install --from-paths src --ignore-src --rosdistro kinetic -y --skip-keys python-wxtools --skip-keys google-mock

ignition-transport3 installation fails.

In High Sierra, Gazebo 9 is successfully installed and works.
But the ignition-transport3 faces compile error due to protobuf version mismatch as below.

> ==> make install
Last 15 lines from /Users/eri/Library/Logs/Homebrew/ignition-transport3/02.make:
make[2]: *** [src/CMakeFiles/ignition-transport3.dir/ign.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
20 errors generated.
make[2]: *** [src/CMakeFiles/ignition-transport3.dir/Node.cc.o] Error 1
20 errors generated.
make[2]: *** [src/CMakeFiles/ignition-transport3.dir/NodeShared.cc.o] Error 1
make[1]: *** [src/CMakeFiles/ignition-transport3.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 15%] Linking CXX static library libgtest.a
cd /tmp/ignition-transport3-20191004-7208-srsy1s/ignition-transport3-3.1.0/test && /usr/local/Cellar/cmake/3.15.3/bin/cmake -P CMakeFiles/gtest.dir/cmake_clean_target.cmake
cd /tmp/ignition-transport3-20191004-7208-srsy1s/ignition-transport3-3.1.0/test && /usr/local/Cellar/cmake/3.15.3/bin/cmake -E cmake_link_script CMakeFiles/gtest.dir/link.txt --verbose=1
/usr/bin/ar qc libgtest.a  CMakeFiles/gtest.dir/gtest/src/gtest-all.cc.o
/usr/bin/ranlib libgtest.a
[ 15%] Built target gtest
make: *** [all] Error 2

**Comment by scpeters** [comment]
ignition-transport3 is used by gazebo8, which is end-of-life and doesn't have working binaries (aka bottles) any longer. If you post the full log from `/Users/eri/Library/Logs/Homebrew/ignition-transport3/02.make` to a gist, I will take a look at it and accept a pull request with patches for this formula, but I won't be planning to fix it due to it's end-of-life status.

**Comment by iPsych** [comment]
> ignition-transport3 is used by gazebo8, which is end-of-life and doesn't have working binaries (aka bottles) any longer. If you post the full log from `/Users/eri/Library/Logs/Homebrew/ignition-transport3/02.make` to a gist, I will take a look at it and accept a pull request with patches for this formula, but I won't be planning to fix it due to it's end-of-life status.

Below is the error log.
https://gist.github.com/iPsych/9f4f1914d8ea23390191bbbaa856096a

I agree that gazebo version is end of life.
Is there any 'updated' formula or codes for replace below?

> rosdep install --from-paths src --ignore-src --rosdistro kinetic -y --skip-keys python-wxtools --skip-keys google-mock

**Comment by scpeters** [comment]
can you try rebuilding `ignition-msgs0`?

`brew reinstall ignition-msgs0`

**Comment by iPsych** [comment]
> can you try rebuilding `ignition-msgs0`?
> 
> `brew reinstall ignition-msgs0`

shows errors as below.

> Last 15 lines from /Users/eri/Library/Logs/Homebrew/ignition-msgs0/01.cmake:
-- BUILD WARNINGS
-- 	Missing: protobuf ruby bindings (sudo gem install protobuf)
-- 	ronn not found, manpages won't be generated
-- END BUILD WARNINGS

-- BUILD ERRORS: These must be resolved before compiling.
-- 	Missing: Ignition math3 library.
-- END BUILD ERRORS

CMake Error at CMakeLists.txt:237 (message):
  Errors encountered in build.  Please see the BUILD ERRORS above.


-- Configuring incomplete, errors occurred!
See also "/tmp/ignition-msgs0-20191004-15013-18vagsy/ignition-msgs-0.7.0/CMakeFiles/CMakeOutput.log".

**Comment by scpeters** [comment]
The reinstall command should have tried to install `ignition-math3`. Perhaps `ignition-math3` is installed but not linked? Can you try `brew link ignition-math3`?

There are conflicts between some versions of ignition-math, so not all of them can be linked to `/usr/local` at the same time.

**Comment by iPsych** [comment]
> The reinstall command should have tried to install `ignition-math3`. Perhaps `ignition-math3` is installed but not linked? Can you try `brew link ignition-math3`?
> 
> There are conflicts between some versions of ignition-math, so not all of them can be linked to `/usr/local` at the same time.

Thanks!
It resolved installation issue.

However, below error displays when I proceed to next step.

> ./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release

I believe it's mismatch between opencv and VTK. homebrew doesn't support vtk5 anymore.
Should I compile and install vtk5 instead homebrew vtk8?

```

/usr/local/Cellar/vtk/8.2.0_3/include/vtk-8.2/vtkSmartPointer.h:113:12: error: 
      static_cast from 'vtkObjectBase *' to 'vtkTexture *', which are not
      related by inheritance, is not allowed
    return static_cast<T*>(this->Object);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/eri/ros_catkin_ws/src/opencv3/modules/viz/src/clouds.cpp:438:27: note: 
      in instantiation of member function 'vtkSmartPointer<vtkTexture>::operator
      vtkTexture *' requested here
        actor->SetTexture(texture);
                          ^
/usr/local/Cellar/vtk/8.2.0_3/include/vtk-8.2/vtkActor.h:41:7: note: 
      'vtkTexture' is incomplete
class vtkTexture;
      ^
11 errors generated.
make[2]: *** [modules/viz/CMakeFiles/opencv_viz.dir/src/clouds.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Users/eri/ros_catkin_ws/src/opencv3/modules/viz/src/shapes.cpp:678:12: error: 
      member access into incomplete type 'vtkTexture'
    texture->SetInputConnection(source->GetOutputPort());
           ^
/usr/local/Cellar/vtk/8.2.0_3/include/vtk-8.2/vtkActor.h:41:7: note: forward
      declaration of 'vtkTexture'
class vtkTexture;
      ^
/Users/eri/ros_catkin_ws/src/opencv3/modules/viz/src/shapes.cpp:726:12: error: 
      member access into incomplete type 'vtkTexture'
    texture->SetInputConnection(source->GetOutputPort());
           ^
/usr/local/Cellar/vtk/8.2.0_3/include/vtk-8.2/vtkActor.h:41:7: note: forward
      declaration of 'vtkTexture'
class vtkTexture;
```

**Comment by scpeters** [comment]
I'm afraid I don't know the answer to that, perhaps you could post to ROS Answers?

If there are no more issues with formulae hosted by this tap, I think the discussion can move elsewhere and this issue can be closed.
